Env: LOCAL

Server:
  mode: debug
  addr: ":8080"
  readTimeout: 600s
  writeTimeout: 600s
  idleTimeout: 60s
  grace: false

Log:
  path: ./log/gin-demo.log
  level: DEBUG

Mysql:
  reader: ""
  writer: ""

Redis:
  addr: ""
  password: ""
  idletimeout: 240
  poolsize: 100
  db: 0
